config/routes.rb
Rails.application.routes.draw do

  resources :products

  get 'home/index'

  devise_for :users
       root to: "home#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	validates :name, presence: true
	validates :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.all
    # respond_with(@products)
  end

  def show
    # respond_with(@product)
  end

  def new
    @product = Product.new
    # respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    # respond_with(@product)
  end

  def update
    @product.update(product_params)
    # respond_with(@product)
  end

  def destroy
    @product.destroy
    # respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<%= render "devise/shared/navbar" %>
<br>	
	<hr>
<br>
<% if current_user.present? %>
	<%= link_to 'Products', products_path %>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="alert alert-info"><%= notice %></div>
 <div class="alert alert-warning"><%= alert %></div>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%=f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render "devise/shared/navbar" %>                      <b>  User: </b> <%= current_user.email %>

<br>
  <hr>
<br>

<h1>Listing products</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <% if product.user_id == current_user.id %> 
            <tr>
              <td><%= product.name %></td>
              <td><%= product.price %></td>
              <td><%= link_to 'Show', product %></td>
              <td><%= link_to 'Edit', edit_product_path(product) %></td>
              <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
<br>
<%= link_to 'Click Here for json Response for api ', '/products.json' %> <br>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

		<p>
		  <strong>Name:</strong>
		  <%= @product.name %>
		</p>

		<p>
		  <strong>Price:</strong>
		  <%= @product.price %>
		</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>